---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer-cluster
rules:
- apiGroups: [""]
  resources: ["configmaps", "deployments", "pods",  "secrets", "services"]
  verbs: ["get", "list", "watch"]