---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: viewer-cluster
subjects:
- kind: Group
  name: viewer-group
  apiGroup: rbac.authorization.k8s.io